<a href="https://colab.research.google.com/github/sbborusu/530pm_Agentic_Ai_Batch_7thApril/blob/main/classwork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
float(23)

23.0

In [ ]:
float(23, 56)

TypeError: float expected at most 1 argument, got 2

In [ ]:
float(False)

In [ ]:
float(1+2j)

In [ ]:
float('10')

In [ ]:
complex(10)

In [ ]:
complex(10,20)

In [ ]:
complex(10,20,30)

In [ ]:
complex(True)

In [ ]:
complex(False)

In [ ]:
complex(True,False)

In [ ]:
bool('1')

In [ ]:
bool(3.2)

In [ ]:
bool(0.0)

In [ ]:
bool(0j)

In [ ]:
bool('_')

In [ ]:
bool(' ')

In [ ]:
bool( )

In [ ]:
bool('$')

In [ ]:
str(10)

In [ ]:
s9='hellopython'
s9[:]

In [ ]:
for i in s9:
  print(i)

In [ ]:
s9[0]

In [ ]:
s9[15]

In [ ]:
s9[::-1]

In [ ]:
s9[0:5]

In [ ]:
s9[0:-1]

In [ ]:
s9[1:20]

In [ ]:
s9[0:]

In [ ]:
s9[:5]

In [ ]:
s9[0:0]

In [ ]:
s9[0:-1]

In [ ]:
s9[0:11:2]

In [ ]:
s9[::]

In [ ]:
s9[::2]

In [ ]:
s9[::-2]

In [ ]:
s9[5:0]

In [ ]:
s9[0::2]

# LIST Data Types

In [ ]:
l = []

In [ ]:
type(l)

In [ ]:
l.append(10)
l.append(20)
l.append(30)
l.append(40)
print(l)
l.clear()

In [ ]:
len(l)

In [ ]:
l1 = l.copy()
l1

In [ ]:
l1.append(2.3)
l1.append('nit')
l1.append(1+2j)
l1.append([1,2,3])
l1

In [ ]:
l2 = l1.copy()
l1 == l2

In [ ]:
l = []
l.append(10)
l.append(20)
l.append(30)
l.append(40)

In [ ]:
l

In [ ]:
l[0]

In [ ]:
l[0] = 100
l[0]

In [ ]:
l

In [ ]:
l[-1] = 200

In [ ]:
l

In [ ]:
l[3:]

In [ ]:
l[5]

In [ ]:
l[5:]

In [ ]:
l[:10]

In [ ]:
l1.clear()
l1

In [ ]:
del l1
l1

In [ ]:
l2 = []
l2.append(10)
l2.append('nit')
l2.append(1+2j)

In [ ]:
l2.append(20)
l2.append(30)
l2.append(40)

In [ ]:
print(l2)

In [ ]:
l1 = [10,20,30,40,50,60,70,'nit','sindhur','borusu',10]
print(l1[8])
print(l1[8][0]) # nested list
print(l1[8][1])

In [ ]:
l1.count(10)

In [ ]:
l1 = [10,20,30,40,50]
l1.insert(2,25)
print(l1)

In [ ]:
l1 = [10,20,30,40,50]
l1[2] = 25
print(l1)

In [ ]:
l1 = [10,20,30,40,50]
l1[2:3] = [25]
print(l1)

In [ ]:
l1 = [10,20,30,40,50]
l1.pop()
print(l1)

In [ ]:
l1 = [10,20,30,40,50]
l1.pop(0) # removes by index
print(l1)

[20, 30, 40, 50]


In [ ]:
l1.sort()
l1

[20, 30, 40, 50]

In [ ]:
l1.sort(reverse=True)
l1

[50, 40, 30, 20]

# April 23

In [ ]:
l6 = ['z', 'x', 'b', 'd']
l6

['z', 'x', 'b', 'd']

In [ ]:
l6.sort() #Parameter tuning
l6

['b', 'd', 'x', 'z']

In [ ]:
l6.sort(reverse=True) #Hyper parameter tuning or

In [ ]:
for i in l6:
  print(i)

z
x
d
b


In [ ]:
'z' in l6 #list membership

True

In [ ]:
for i in enumerate(l6):
  print(i)

(0, 'z')
(1, 'x')
(2, 'd')
(3, 'b')


In [ ]:
all(l6)

True

In [ ]:
any(l6)

True

#tuple

In [ ]:
t1 = (10,20,30,40,50)
t1

(10, 20, 30, 40, 50)

In [ ]:
t2 = ('a', 'z', 'm', 'n', 'n', 10)
t2

('a', 'z', 'm', 'n', 'n', 10)

In [ ]:
t2.count('z')

1

In [ ]:
t2.index('a')

0

In [ ]:
t1[0] = 10

TypeError: 'tuple' object does not support item assignment

In [ ]:
t1 [0]

10

In [ ]:
l1 = []
l1 = t1
l1

(10, 20, 30, 40, 50)

In [ ]:
type(l1)

tuple

In [ ]:
l2 = []
l2.extend(t1)
l2

[10, 20, 30, 40, 50]

In [ ]:
3 + 'nit'

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [ ]:
'nit' + 3

TypeError: can only concatenate str (not "int") to str

In [ ]:
3 * 'nit'

'nitnitnit'

# Set

In [ ]:
s = {}
s
type(s)

dict

In [ ]:
s1 = set()
type(s1)

set

In [ ]:
s1.add(10)
s1

{10}

In [ ]:
s1.add(20)
s1.add('nit')
s1.add(True)
s1.add(1+2j)
s1.add(3.2)
s1

{(1+2j), 10, 20, 3.2, True, 'nit'}

In [ ]:
s3 = {100,10,20}
s3

{10, 20, 100}

In [ ]:
type(s2)

set

In [ ]:
print(len(s3))

3


In [ ]:
s3[0]

TypeError: 'set' object is not subscriptable

In [ ]:
s3{::}

SyntaxError: invalid syntax (<ipython-input-13-983de58317b3>, line 1)

In [ ]:
s4=s3.copy()

In [ ]:
s3 == s4

True

In [ ]:
s4.pop()

10

In [ ]:
s4.pop(0)

TypeError: set.pop() takes no arguments (1 given)

# Set operations

In [ ]:
for i in s4:
  print(i)

100
20


In [ ]:
for i in enumerate(s4):
  print(i)

(0, 100)
(1, 20)


In [ ]:
A = {1,2,3,4,5}
B = {4,5,6,7,8}
C = {8,9,10}

In [ ]:
A | B #Union

{1, 2, 3, 4, 5, 6, 7, 8}

In [ ]:
B.union(C)

{4, 5, 6, 7, 8, 9, 10}

In [ ]:
A.union(B,C)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

In [ ]:
A | B | C

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

In [ ]:
D = C.copy()
D

{8, 9, 10}

In [ ]:
print(C)
print(D)

{8, 9, 10}
{8, 9, 10}


In [ ]:
C.update(B)
print(C)
print(B)

{4, 5, 6, 7, 8, 9, 10}
{4, 5, 6, 7, 8}


# Numpy

In [1]:
import numpy as np

In [3]:
np.__version__

'2.0.2'

In [4]:
import sys
sys.version

'3.11.12 (main, Apr  9 2025, 08:55:54) [GCC 11.4.0]'

## Create Lists

In [5]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [6]:
type(my_list)

list

# Convert list to array

In [8]:
arr = np.array(my_list)
type(arr)

numpy.ndarray

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [14]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
np.arange(1,5)

array([1, 2, 3, 4])

In [17]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [21]:
np.arange(20,10) # empty array since 1st arg is greater than 2nd

array([], dtype=int64)

In [22]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [23]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [24]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [25]:
np.zeros(10) # Gives an array of all zeros. This is parameter tuning.

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
np.zeros(10,dtype=int) # hyper-parameter tuning or fine tuning

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
np.zeros((2,2),dtype=int) # 2D array

array([[0, 0],
       [0, 0]])

In [31]:
np.zeros((3,4), dtype=int) #multi dimentional array

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [33]:
np.zeros((10,20))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [34]:
np.ones(3)

array([1., 1., 1.])

In [35]:
np.ones((4,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [36]:
np.twos((2,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [37]:
rand(3,2)

NameError: name 'rand' is not defined

In [38]:
random.rand(3,2)

NameError: name 'random' is not defined

In [43]:
np.random.rand(3,2)

array([[0.15965947, 0.09045925],
       [0.00260003, 0.61565846],
       [0.39914399, 0.02394979]])

In [44]:
np.random.rand(3,5) # generates array and will be random each tim

array([[0.97883204, 0.52707232, 0.79854097, 0.63432648, 0.01329859],
       [0.51878181, 0.07833265, 0.84089919, 0.89496469, 0.89518141],
       [0.37444136, 0.94289828, 0.2047765 , 0.95362642, 0.18852161]])

In [57]:
np.random.randint(4,10) # generates random integer between the range

6

In [60]:
np.random.randint(2,20)

13

In [64]:
np.random.randint(2,20,5) #generates 5 random numbers as array

array([ 2, 10, 13,  7, 14])

In [65]:
np.random.randint(10,20,5)

array([17, 16, 11, 12, 16])

In [67]:
np.random.randint(10,40,(10,5))

array([[15, 29, 10, 14, 28],
       [14, 27, 36, 10, 19],
       [13, 34, 11, 21, 17],
       [28, 36, 11, 21, 27],
       [34, 20, 33, 39, 21],
       [23, 23, 32, 34, 25],
       [22, 27, 20, 19, 21],
       [26, 38, 13, 34, 29],
       [35, 13, 28, 36, 26],
       [15, 32, 30, 15, 10]])

In [68]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [71]:
np.arange(1,13).reshape(3,4) # arrages elements in 3 x 4 = 12

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [72]:
np.arange(1,13).reshape(6,3) # cannot arrage as elements dont match 6 X 3 = 18

ValueError: cannot reshape array of size 12 into shape (6,3)

## Slicing in matrix