<a href="https://colab.research.google.com/github/sbborusu/530pm_Agentic_Ai_Batch_7thApril/blob/main/Machine_Learning_Preprocessing_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Gather Data

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_csv(r'/content/Data (1).csv')


# Split the data set into x and y variables

In [ ]:
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 3].values

In [ ]:
x

array([['Mumbai', 44.0, 72000.0],
       ['Bangalore', 27.0, 48000.0],
       ['Hyderabad', 30.0, 54000.0],
       ['Bangalore', 38.0, 61000.0],
       ['Hyderabad', 40.0, nan],
       ['Mumbai', 35.0, 58000.0],
       ['Bangalore', nan, 52000.0],
       ['Mumbai', 48.0, 79000.0],
       ['Hyderabad', 50.0, 83000.0],
       ['Mumbai', 37.0, 67000.0]], dtype=object)

In [ ]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

# Perform imputation i.e., null value treatment




In [ ]:
# Instead of fillna to impute, we can use SimpleImputer to treat/impute missing values.
from sklearn.impute import SimpleImputer
imputer = SimpleImputer() # by default the strategy is mean and 'most_frequent' is mode. This strategy is hyper parameter tuning
# or fine tuning.
imputer = imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])


# Convert categorical data to numerical

In [ ]:
# Convert categorical data into numerical
from sklearn.preprocessing import LabelEncoder
labelencoder_x = LabelEncoder()
x[:,0] = labelencoder_x.fit_transform(x[:,0])

In [ ]:
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

# Split data into x-train, x-test, y-train, y-test

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8, test_size = 0.2, random_state = 0) # random_state will make sure same data split is
# picked up during multiple runs
print(x_train)
print("")
print(x_test)
print("")
print(y_train)
print("")
print(y_test)

[[1 40.0 63777.77777777778]
 [2 37.0 67000.0]
 [0 27.0 48000.0]
 [0 38.77777777777778 52000.0]
 [2 48.0 79000.0]
 [0 38.0 61000.0]
 [2 44.0 72000.0]
 [2 35.0 58000.0]]

[[1 30.0 54000.0]
 [1 50.0 83000.0]]

[1 1 1 0 1 0 0 1]

[0 0]
