<a href="https://colab.research.google.com/github/sbborusu/530pm_Agentic_Ai_Batch_7thApril/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr1D = np.array([1,2,3,4]) # 1D array
arr1D

array([1, 2, 3, 4])

In [ ]:
arr2D_1 = np.array([[1,2,3],[4,5,6]]) # 2D 2 X 3 matrix
arr2D_1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2D_2 = np.array([[1,2],[4,5],[7,8]]) # 2D 3 X 2 matrix
arr2D_2

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6,7]]) # All rows in a 2D array must have the same number of columns
arr1

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
arr1 = np.array([[1,2,3,None],[4,5,6,7]]) # ou can pad the shorter rows with a placeholder value (like None or 0) to make all rows the same length:
arr1

array([[1, 2, 3, None],
       [4, 5, 6, 7]], dtype=object)

# Access a 2D array

In [ ]:
range(10,100,10)
arr = np.array([1,2,3],dtype='int',ndmin=2)
print(arr)
print(arr[0])
print(arr[0][0])
print(arr.ndim)
arr2 = np.array([[1,2,3],[4,5,6]],ndmin=2)
print(arr2)

[[1 2 3]]
[1 2 3]
1
2
[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.array([1,2,3, 'sindhur'],dtype=int)

ValueError: invalid literal for int() with base 10: 'sindhur'

In [ ]:
arr4 = np.array([[1,2,3,10], [4,5,6,20], [7,8,9,30]])
print(arr4) # This prints the entire 2D array
print(arr4[0]) # This prints the first row of the array:
print(arr4[0:2]) # This prints the first two rows of the array:
print(arr4[1][2]) # This prints the element in the second row and third column:
print(arr4[1,2]) # This also prints the element in the second row and third column, using a different indexing method
print(arr4[0:2,1:3]) #This prints a subarray consisting of the first two rows and the second and third columns
print(arr4[:,2]) #This prints the third column of the array
print(arr4[:,2].reshape(-1,1)) #This prints the third column in a column format

[[ 1  2  3 10]
 [ 4  5  6 20]
 [ 7  8  9 30]]
[ 1  2  3 10]
[[ 1  2  3 10]
 [ 4  5  6 20]]
6
6
[[2 3]
 [5 6]]
[3 6 9]
[[3]
 [6]
 [9]]


# reshape an array

In [ ]:
arr5 = np.array([1,2,3,4,6,7])
print(arr5)
print(arr5.reshape(2,3))
print(arr5.reshape(-1,3)) # -1 indicates numpy to figure out the number of rows based on columns needed.
print(arr5.reshape(3,-1)) # -1 indicates numpy to figure out the number of columns based on rows needed.
arr6 = np.array([[1,2],[3,4]])
print(arr6.reshape(-1)) # reshape(-1) flattens the 2D array into a 1D array. The -1 parameter tells NumPy to automatically calculate the size of the new dimension based on the total number of elements.

[1 2 3 4 6 7]
[[1 2 3]
 [4 6 7]]
[[1 2 3]
 [4 6 7]]
[[1 2]
 [3 4]
 [6 7]]
[1 2 3 4]


# Random and Random int

In [ ]:
print(np.random.randint(5)) # Generates a random integer below 5
print(np.random.randint(5, 10)) # Generates a random integer below 5(inclusive) and 10(exclusive)
print(np.random.randint(2, size=5)) # Generates a 1D array of size 5 with elements below 2
print(np.random.randint(0,20,4)) # Generates a random list of integers between 0(inclusive) and 20(exclusive). Number of elements in list is third parameter
print(np.random.randint(0,20,(10,10))) # Generates a random array of 10 x 10 matrix integers between 0(inclusive) and 20(exclusive).


0
5
[0 1 1 0 1]
[18  3 12 12]
[[ 7 16 10  4  7 11  0  8 11  8]
 [14  1 12 15  4 17 12 12  2  0]
 [17  4  7 16 15  8  0  9 10 14]
 [15 14  6  7  7  5  1  0 11  6]
 [ 0  9  1 18  4  4  6  1  5 19]
 [16 15  0  2 13  2 19 14  8  7]
 [17  7  6  4 14 12 19 15  4 19]
 [ 6 13  9 14 17  8  2 18  9  6]
 [16 17 18 12  8 19 19  5  1 16]
 [ 5 17  2 12 14 13  2 15 16  7]]


In [ ]:
print(np.random.rand()) # Generates a single float between 0 and 1
print(np.random.rand(3)) # Generates a 1D array with values between 0 and 1. 3 indicates number of elements in the array.
print(np.random.rand(3,2)) # Generates a 2D array with values between 0 and 1. 3,2 indicates 3 rows 2 columns matrix.
print(np.random.rand(3,2,3)) # Generates a 3D array with values between 0 and 1.

0.8936279202296217
[0.78836719 0.28205927 0.53731237]
[[0.56573862 0.74881568]
 [0.15174448 0.70420818]
 [0.71832383 0.31231544]]
[[[0.65441146 0.60807219 0.16620275]
  [0.1509855  0.33306105 0.95555295]]

 [[0.65059403 0.86508888 0.66083306]
  [0.5570284  0.75542139 0.6617841 ]]

 [[0.74949549 0.46621232 0.70130251]
  [0.54131914 0.42475469 0.3824949 ]]]


In [ ]:
print(np.ones(5))
print(np.ones(5,dtype=str))
print(np.ones(5,dtype=bool))
print(np.ones(5,dtype=int))
print(np.ones(5,dtype=complex))
print(np.ones((3,2)))
print(np.ones((3,2,4)))

[1. 1. 1. 1. 1.]
['1' '1' '1' '1' '1']
[ True  True  True  True  True]
[1 1 1 1 1]
[1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [ ]:
print(np.zeros(5))
print(np.zeros(5,dtype=str))
print(np.zeros(5,dtype=bool))
print(np.zeros(5,dtype=int))
print(np.zeros(5,dtype=complex))
print(np.zeros((3,2)))
print(np.zeros((3,2,4)))

[0. 0. 0. 0. 0.]
['' '' '' '' '']
[False False False False False]
[0 0 0 0 0]
[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


# ND Arrays

In [ ]:
# 3D array
arr3d = np.array([[[2,3,1],[4,5,2]], [[4,2,1],[6,2,3]], [[5,3,1],[8,9,2]]]) # 3 layers, 2 rows, 3 columns
print(arr3d.ndim)
print(arr3d)
print(arr3d[0][0])
print(arr3d[0][0:2])
print(arr3d[1][1][0])
print(arr3d[1][1,0])
print(arr3d[0][0:2,0:2])
print(arr3d[0][:,:])
print(arr3d[0][:,0:1])
print(arr3d[0][:,0:1].reshape(-1,1))

3
[[[2 3 1]
  [4 5 2]]

 [[4 2 1]
  [6 2 3]]

 [[5 3 1]
  [8 9 2]]]
[2 3 1]
[[2 3 1]
 [4 5 2]]
6
6
[[2 3]
 [4 5]]
[[2 3 1]
 [4 5 2]]
[[2]
 [4]]
[[2]
 [4]]


# Images, Text, Speech inputs AI will internally get converted into multi-dimentional arrays

In [ ]:
image_array = np.random.rand(3,4,2) # 3D array with 3 layers, 4 rows, 2 columns
print(image_array.ndim)
print(image_array)
print(image_array[0])

3
[[[0.17889944 0.28193276]
  [0.94835376 0.42112249]
  [0.47450945 0.63192733]
  [0.09168105 0.92544047]]

 [[0.72817638 0.83133594]
  [0.32505033 0.25800687]
  [0.77175561 0.13979451]
  [0.63219724 0.21820612]]

 [[0.89882875 0.74019029]
  [0.80285385 0.13545466]
  [0.15479938 0.92925165]
  [0.31334914 0.80563073]]]
[[0.17889944 0.28193276]
 [0.94835376 0.42112249]
 [0.47450945 0.63192733]
 [0.09168105 0.92544047]]


In [ ]:

text_data = np.array(['hello', 'world'])

In [ ]:
print(text_data.reshape(2,1))
print(text_data.reshape(-1,1))

[['hello']
 ['world']]
[['hello']
 ['world']]


In [ ]:
num_data = np.array([1,2,3,4,5,6])
reshpaed_data = num_data.reshape(2,3)
reshpaed_data1 = num_data.reshape((2,3))
print(num_data)
print(reshpaed_data)
print(reshpaed_data1)
reshpaed_data_c_type = num_data.reshape(2,3,order='C') #Taking the input, the rows are filled first in the reshaped array
print(reshpaed_data_c_type)
reshpaed_data_F_type = num_data.reshape(2,3,order='F') #Taking the input, the columns are filled first in the reshaped array
print(reshpaed_data_F_type)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 3 5]
 [2 4 6]]


In [ ]:
# Arrays vs Lists ()

In [ ]:
import numpy as np
import sys

# Python list
lst = [1, 2, 3]
print("List element addresses:")
for i in lst:
    print(sys.getsizeof(i), id(i)) # Notice the memory locations are far from each other and are scattered in memory

# NumPy array
arr = np.array([1, 2, 3])
print("\nNumPy array element addresses:")
for i in arr:
    print(sys.getsizeof(i), id(i)) # Notice the memory locations show close to each other and contigeous.


List element addresses:
28 10750856
28 10750888
28 10750920

NumPy array element addresses:
32 137761836792912
32 137761836792624
32 137761836792912


In [ ]:
import numpy as np
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(a1 * a2)
print(type(a1 * a2))
print(np.dot(a1,a2))
print(type(np.dot(a1,a2)))


a21 = np.array([[1,2,3], [4,5,6]])
print(a21.shape)
a22 = np.array([[1,2,3], [4,5,3], [5,6,3]])
#print(a21 * a22)
print(np.dot(a21,a22))
print(np.dot(a21,a22))

[ 4 10 18]
<class 'numpy.ndarray'>
32
<class 'numpy.int64'>
(2, 3)
[[24 30 18]
 [54 69 45]]
[[24 30 18]
 [54 69 45]]


In [ ]:
import numpy as np
mixed_array = np.array([1, 'hello', 3.14, True])
print(mixed_array)
print(mixed_array.dtype)

['1' 'hello' '3.14' 'True']
<U32


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
# copies owns the data, and views does not own the data, but how can we check this?
# Every NumPy array has the attribute base that returns None if the array owns the data.
# Otherwise, the base  attribute refers to the original object.
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [ ]:
import numpy as np

arr_1d = np.array([1, 2, 3, 4], ndmin=1)
print(arr_1d)
print('shape of array :', arr.shape)

arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr_2d.shape)
print(type(arr_2d.shape))

arr_3d = np.array([1, 2, 3, 4], ndmin=3)
print(arr_3d)
print('shape of array :', arr_3d.shape)

[1 2 3 4]
shape of array : (4,)
(2, 4)
<class 'tuple'>
[[[1 2 3 4]]]
shape of array : (1, 1, 4)


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base)
arr1 = arr.reshape(2,4).view()
print(arr)
print(arr1)
print(arr1[1,1])
arr1[1,1] = 66
print(arr)
print(arr1)
print(arr.reshape(2, 4).base)


[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
6
[ 1  2  3  4  5 66  7  8]
[[ 1  2  3  4]
 [ 5 66  7  8]]
[ 1  2  3  4  5 66  7  8]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(1,-1)
newarr1 = arr.reshape(-1)
newarr2 = arr.reshape(6)
newarr3 = arr.flatten()


print(newarr)
print(newarr1)
print(newarr2)
print(newarr3)

[[1 2 3 4 5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [ ]:
import numpy as np

# Access 1D array in for loop
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

print('')

# Access 2D array in for loop
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

print('')

# Access 3D array in for loop
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3

1
2
3
4
5
6

1
2
3
4
5
6
7
8
9
10
11
12


# nditer

In [ ]:
import numpy as np

# Access 3D array in for loop without nditer
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

print('')
# Access 3D array in for loop with nditer

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8
9
10
11
12

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
import numpy as np
arr = np.array([[1, 2],
                [3, 4]])
print(arr.T)
# Output:
# [[1, 3],
#  [2, 4]]
print('')
arr_3d = np.array([[[1, 2, 3,24], [4, 5, 6,34], [13,14,15,44]], [[7, 8, 9, 93], [10, 11, 12, 83], [33,43,53,63]]])
print(arr_3d)
print(arr_3d.shape)
arr_3d.transpose(2,0,1)
print(arr_3d)
print(arr_3d.shape)

[[1 3]
 [2 4]]

[[[ 1  2  3 24]
  [ 4  5  6 34]
  [13 14 15 44]]

 [[ 7  8  9 93]
  [10 11 12 83]
  [33 43 53 63]]]
(2, 3, 4)
[[[ 1  2  3 24]
  [ 4  5  6 34]
  [13 14 15 44]]

 [[ 7  8  9 93]
  [10 11 12 83]
  [33 43 53 63]]]
(2, 3, 4)


In [ ]:
arr = np.array([[1, 2], [3, 4]])
arr + 10
# Output:
# [[11, 12],
#  [13, 14]]


array([[11, 12],
       [13, 14]])

In [ ]:
arr = np.array([[1, 2], [3, 4]])
row = np.array([10, 20])
arr + row
# Output:
# [[11, 22],
#  [13, 24]]


array([[11, 22],
       [13, 24]])

In [ ]:
arr = np.array([[[1, 2], [3, 4]], [[2,3], [3,4]]])
row = np.array([[10, 20]])
arr + row
# Output:
# [[11, 22],
#  [13, 24]]


array([[[10, 40],
        [30, 80]],

       [[20, 60],
        [30, 80]]])

In [ ]:
arr = np.array([[[1, 2], [3, 4]], [[2,3], [3,4]]])
row = np.array([[10, 20], [30, 40]])
arr + row
# Output:
# [[11, 22],
#  [13, 24]]


array([[[11, 22],
        [33, 44]],

       [[12, 23],
        [33, 44]]])

# This is NumPy's multi-dimensional iterator. It allows you to iterate over arrays efficiently, even with complex operations.

flags=['buffered']: This tells nditer to use an internal buffer. This is required when you're changing the data type during iteration (as you're doing here).
op_dtypes=['S']: This tells nditer to cast each element to a string of bytes (i.e., a byte string). 'S' is shorthand for a byte string data type in NumPy (like np.string_).

In [1]:
import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)
  print(x.ndim)
  print(x.shape)
  print(x.dtype)

np.bytes_(b'1')
0
()
|S21
np.bytes_(b'2')
0
()
|S21
np.bytes_(b'3')
0
()
|S21


In [11]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# Iterate through every scalar element of the 2D array skipping 1 element:
# arr[:, ::2]
# :    - indicates all rows
# ::2  - indicates step count of 2 from all rows identified
for x in np.nditer(arr[:, ::2]):
  print(x)

print('')

# Iterate through every scalar element of the 2D array skipping 1 element:
# arr[0:1, ::2]
# 0:1  - indicates first row alone
# ::2  - indicates step count of 2 from all rows identified
for x in np.nditer(arr[0:1, ::2]):
  print(x)

print("")
# Iterate through every scalar element of the 2D array skipping 1 element:
# arr[:, 1::2]
# :    - indicates all rows
# 1::2 - indicates step count of 2 from all rows start at index 1
for x in np.nditer(arr[:, 1::2]):
  print(x)

1
3
5
7

1
3

2
4
6
8


#enumerate vs ndenumerate

In [12]:
import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx)
  print(x)

print("")

lst = [1,2,3]

for idx, x in enumerate(lst):
  print(idx)
  print(x)


(0,)
1
(1,)
2
(2,)
3

0
1
1
2
2
3
