<a href="https://colab.research.google.com/github/sbborusu/530pm_Agentic_Ai_Batch_7thApril/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr1D = np.array([1,2,3,4]) # 1D array
arr1D

array([1, 2, 3, 4])

In [3]:
arr2D_1 = np.array([[1,2,3],[4,5,6]]) # 2D 2 X 3 matrix
arr2D_1

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
arr2D_2 = np.array([[1,2],[4,5],[7,8]]) # 2D 3 X 2 matrix
arr2D_2

array([[1, 2],
       [4, 5],
       [7, 8]])

In [5]:
arr1 = np.array([[1,2,3],[4,5,6,7]]) # All rows in a 2D array must have the same number of columns
arr1

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [7]:
arr1 = np.array([[1,2,3,None],[4,5,6,7]]) # ou can pad the shorter rows with a placeholder value (like None or 0) to make all rows the same length:
arr1

array([[1, 2, 3, None],
       [4, 5, 6, 7]], dtype=object)

# Access a 2D array

In [8]:
range(10,100,10)
arr = np.array([1,2,3],dtype='int',ndmin=2)
print(arr)
print(arr[0])
print(arr[0][0])
print(arr.ndim)
arr2 = np.array([[1,2,3],[4,5,6]],ndmin=2)
print(arr2)

[[1 2 3]]
[1 2 3]
1
2
[[1 2 3]
 [4 5 6]]


In [9]:
arr = np.array([1,2,3, 'sindhur'],dtype=int)

ValueError: invalid literal for int() with base 10: 'sindhur'

In [10]:
arr4 = np.array([[1,2,3,10], [4,5,6,20], [7,8,9,30]])
print(arr4) # This prints the entire 2D array
print(arr4[0]) # This prints the first row of the array:
print(arr4[0:2]) # This prints the first two rows of the array:
print(arr4[1][2]) # This prints the element in the second row and third column:
print(arr4[1,2]) # This also prints the element in the second row and third column, using a different indexing method
print(arr4[0:2,1:3]) #This prints a subarray consisting of the first two rows and the second and third columns
print(arr4[:,2]) #This prints the third column of the array
print(arr4[:,2].reshape(-1,1)) #This prints the third column in a column format

[[ 1  2  3 10]
 [ 4  5  6 20]
 [ 7  8  9 30]]
[ 1  2  3 10]
[[ 1  2  3 10]
 [ 4  5  6 20]]
6
6
[[2 3]
 [5 6]]
[3 6 9]
[[3]
 [6]
 [9]]


# reshape an array

In [11]:
arr5 = np.array([1,2,3,4,6,7])
print(arr5)
print(arr5.reshape(2,3))
print(arr5.reshape(-1,3)) # -1 indicates numpy to figure out the number of rows based on columns needed.
print(arr5.reshape(3,-1)) # -1 indicates numpy to figure out the number of columns based on rows needed.
arr6 = np.array([[1,2],[3,4]])
print(arr6.reshape(-1)) # reshape(-1) flattens the 2D array into a 1D array. The -1 parameter tells NumPy to automatically calculate the size of the new dimension based on the total number of elements.

[1 2 3 4 6 7]
[[1 2 3]
 [4 6 7]]
[[1 2 3]
 [4 6 7]]
[[1 2]
 [3 4]
 [6 7]]
[1 2 3 4]


# Random and Random int

In [12]:
print(np.random.randint(5)) # Generates a random integer below 5
print(np.random.randint(5, 10)) # Generates a random integer below 5(inclusive) and 10(exclusive)
print(np.random.randint(2, size=5)) # Generates a 1D array of size 5 with elements below 2
print(np.random.randint(0,20,4)) # Generates a random list of integers between 0(inclusive) and 20(exclusive). Number of elements in list is third parameter
print(np.random.randint(0,20,(10,10))) # Generates a random array of 10 x 10 matrix integers between 0(inclusive) and 20(exclusive).


2
9
[0 1 0 1 0]
[12  1 13  0]
[[19  1  7  7 11 14  8 16 19 15]
 [18 14 18 13 16  7 12  5  5 16]
 [ 6  7  5  3  2 13  4  4  9  4]
 [ 3 12  9 13  2  8 17  5  4 10]
 [12  5 15  2  6 19 18 18  8  2]
 [ 3  8  7 12  9 13  8  1  8  6]
 [ 3 10  1  1  6  4 18 13  7  7]
 [ 6 13  1 12 13 14  5  1 11  2]
 [ 7 14  6 17  2 15 11 15  3  1]
 [ 3 19 19 16 11 11  4 13  9 10]]


In [38]:
print(np.random.rand()) # Generates a single float between 0 and 1
print(np.random.rand(3)) # Generates a 1D array with values between 0 and 1. 3 indicates number of elements in the array.
print(np.random.rand(3,2)) # Generates a 2D array with values between 0 and 1. 3,2 indicates 3 rows 2 columns matrix.
print(np.random.rand(3,2,3)) # Generates a 3D array with values between 0 and 1.

0.25177678540081105
[0.72692677 0.88528981 0.12525915]
[[0.59100463 0.99301476]
 [0.51528647 0.28967005]
 [0.66834664 0.9227482 ]]
[[[0.30376415 0.79158029 0.81493925]
  [0.63026497 0.38134954 0.03594815]]

 [[0.21690249 0.77307987 0.72274763]
  [0.59114507 0.16120163 0.93666869]]

 [[0.26113497 0.05719438 0.28566211]
  [0.85697048 0.33773809 0.37882172]]]


In [51]:
print(np.ones(5))
print(np.ones(5,dtype=str))
print(np.ones(5,dtype=bool))
print(np.ones(5,dtype=int))
print(np.ones(5,dtype=complex))
print(np.ones((3,2)))
print(np.ones((3,2,4)))

[1. 1. 1. 1. 1.]
['1' '1' '1' '1' '1']
[ True  True  True  True  True]
[1 1 1 1 1]
[1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [53]:
print(np.zeros(5))
print(np.zeros(5,dtype=str))
print(np.zeros(5,dtype=bool))
print(np.zeros(5,dtype=int))
print(np.zeros(5,dtype=complex))
print(np.zeros((3,2)))
print(np.zeros((3,2,4)))

[0. 0. 0. 0. 0.]
['' '' '' '' '']
[False False False False False]
[0 0 0 0 0]
[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


# ND Arrays

In [67]:
# 3D array
arr3d = np.array([[[2,3,1],[4,5,2]], [[4,2,1],[6,2,3]], [[5,3,1],[8,9,2]]]) # 3 layers, 2 rows, 3 columns
print(arr3d.ndim)
print(arr3d)
print(arr3d[0][0])
print(arr3d[0][0:2])
print(arr3d[1][1][0])
print(arr3d[1][1,0])
print(arr3d[0][0:2,0:2])
print(arr3d[0][:,:])
print(arr3d[0][:,0:1])
print(arr3d[0][:,0:1].reshape(-1,1))

3
[[[2 3 1]
  [4 5 2]]

 [[4 2 1]
  [6 2 3]]

 [[5 3 1]
  [8 9 2]]]
[2 3 1]
[[2 3 1]
 [4 5 2]]
6
6
[[2 3]
 [4 5]]
[[2 3 1]
 [4 5 2]]
[[2]
 [4]]
[[2]
 [4]]


# Images, Text, Speech inputs AI will internally get converted into multi-dimentional arrays

In [97]:
image_array = np.random.rand(3,4,2) # 3D array with 3 layers, 4 rows, 2 columns
print(image_array.ndim)
print(image_array)
print(image_array[0])

3
[[[0.56551472 0.63805554]
  [0.91072073 0.34266487]
  [0.88801184 0.61650597]
  [0.50967534 0.51813245]]

 [[0.98478646 0.40089153]
  [0.69856055 0.770159  ]
  [0.84730537 0.26680403]
  [0.5154633  0.42421665]]

 [[0.22383891 0.70305163]
  [0.85164989 0.40571669]
  [0.0379242  0.98265396]
  [0.96118485 0.48074076]]]
[[0.56551472 0.63805554]
 [0.91072073 0.34266487]
 [0.88801184 0.61650597]
 [0.50967534 0.51813245]]
