<a href="https://colab.research.google.com/github/sbborusu/530pm_Agentic_Ai_Batch_7thApril/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [17]:
arr1D = np.array([1,2,3,4]) # 1D array
arr1D

array([1, 2, 3, 4])

In [18]:
arr2D_1 = np.array([[1,2,3],[4,5,6]]) # 2D 2 X 3 matrix
arr2D_1

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
arr2D_2 = np.array([[1,2],[4,5],[7,8]]) # 2D 3 X 2 matrix
arr2D_2

array([[1, 2],
       [4, 5],
       [7, 8]])

In [20]:
arr1 = np.array([[1,2,3],[4,5,6,7]]) # All rows in a 2D array must have the same number of columns
arr1

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [21]:
arr1 = np.array([[1,2,3,None],[4,5,6,7]]) # ou can pad the shorter rows with a placeholder value (like None or 0) to make all rows the same length:
arr1

array([[1, 2, 3, None],
       [4, 5, 6, 7]], dtype=object)

# Access a 2D array

In [55]:
range(10,100,10)
arr = np.array([1,2,3],dtype='int',ndmin=2)
print(arr)
print(arr[0])
print(arr[0][0])
print(arr.ndim)
arr2 = np.array([[1,2,3],[4,5,6]],ndmin=2)
print(arr2)

[[1 2 3]]
[1 2 3]
1
2
[[1 2 3]
 [4 5 6]]


In [56]:
arr = np.array([1,2,3, 'sindhur'],dtype=int)

ValueError: invalid literal for int() with base 10: 'sindhur'

In [84]:
arr4 = np.array([[1,2,3,10], [4,5,6,20], [7,8,9,30]])
print(arr4) # This prints the entire 2D array
print(arr4[0]) # This prints the first row of the array:
print(arr4[0:2]) # This prints the first two rows of the array:
print(arr4[1][2]) # This prints the element in the second row and third column:
print(arr4[1,2]) # This also prints the element in the second row and third column, using a different indexing method
print(arr4[0:2,1:3]) #This prints a subarray consisting of the first two rows and the second and third columns
print(arr4[:,2]) #This prints the third column of the array
print(arr4[:,2].reshape(-1,1)) #This prints the third column in a column format

[[ 1  2  3 10]
 [ 4  5  6 20]
 [ 7  8  9 30]]
[ 1  2  3 10]
[[ 1  2  3 10]
 [ 4  5  6 20]]
6
6
[[2 3]
 [5 6]]
[3 6 9]
[[3]
 [6]
 [9]]


# reshape an array

In [93]:
arr5 = np.array([1,2,3,4,6,7])
print(arr5)
print(arr5.reshape(2,3))
print(arr5.reshape(-1,3)) # -1 indicates numpy to figure out the number of rows based on columns needed.
print(arr5.reshape(3,-1)) # -1 indicates numpy to figure out the number of columns based on rows needed.
arr6 = np.array([[1,2],[3,4]])
print(arr6.reshape(-1)) # reshape(-1) flattens the 2D array into a 1D array. The -1 parameter tells NumPy to automatically calculate the size of the new dimension based on the total number of elements.

[1 2 3 4 6 7]
[[1 2 3]
 [4 6 7]]
[[1 2 3]
 [4 6 7]]
[[1 2]
 [3 4]
 [6 7]]
[1 2 3 4]


# Random and Random int

In [127]:
print(np.random.randint(5)) # Generates a random integer below 5
print(np.random.randint(5, 10)) # Generates a random integer below 5(inclusive) and 10(exclusive)
print(np.random.randint(2, size=5)) # Generates a 1D array of size 5 with elements below 2
print(np.random.randint(0,20,4)) # Generates a random list of integers between 0(inclusive) and 20(exclusive). Number of elements in list is third parameter
print(np.random.randint(0,20,(10,10))) # Generates a random array of 10 x 10 matrix integers between 0(inclusive) and 20(exclusive).

3
9
[0 0 1 1 1]
[ 6 10 10  3]
[[ 8 14 10 15  9 16 11  7  6  7]
 [ 1 15  5  7 16 19 10 13  1 15]
 [15  4 18 16  9  5 12 11 14 13]
 [ 7 14  9 12  8 17 18 19 13  1]
 [11  2  8 10  6  2  4  2 18  0]
 [ 0  8 11 17  5 15  4  9  7  4]
 [10  9 17  2 18 10 19  6  2 19]
 [19 14  4 17  8  7  9 15 14 14]
 [11 12  2 19 17 18  3 13  3  4]
 [ 9 19  8  8  7 12 15  2  9 14]]
